[project]
name = "customersupportsystem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.10.1",
    "gspread>=6.2.1",
    "mcp[cli]>=1.10.1",
    "oauth2client>=4.1.3",
]
