[project]
name = "bookandyoutubesummarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "euriai>=0.3.30",
    "langchain>=0.3.26",
    "mcp[cli]>=1.10.1",
    "youtube-transcript-api>=1.1.0",
]
